### ISSUE TITLE
CLDF metadata.json has empty creator?

### ISSUE THREAD

**Issue by SimonGreenhill** [Anaphory/lexirumah-data#108]
e.g. [here](https://github.com/lessersunda/lexirumah-data/blob/with_lexi_data/cldf/cldf-metadata.json#L15)

```
    "dc:creator": [
        "Gereon A. Kaiping",
        "Owen Edwards",
        "Marian Klamer",
        "",
        "Jiang Wu"
    ],
```

**Comment by Anaphory** [comment]
Oh, right. That was an attempt to hack the shape of that field to separate creators and contributors. There is probably a clean way to do that, do you know it or do I go looking myself?

**Comment by SimonGreenhill** [comment]
DC should have `dc:contributor`, right? @xrotwang

**Comment by Anaphory** [comment]
[It does](http://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-contributor). I'll fix it.

**Comment by SimonGreenhill** [comment]
Thanks!
