### ISSUE TITLE
change ids

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#113]
change the concept ids from an arbitrary number to lectID-conceptID-number

So Central Lembata, Lewuka /wəli/ ‘at’ currently with ID 31013 will become:

lama1277-lewuk-at-1

Every ID has a number, starting at 1. 2 would be used when a languages has ‘synonyms’

**Comment by Anaphory** [comment]
This will break backwards compatibility, so it will be implemented not before version 3.0.0

**Comment by Anaphory** [comment]
This is done now, with the major version number increment also done.
