### ISSUE TITLE
Which release to include in CLICS3?

### ISSUE THREAD

**Issue by xrotwang** [Anaphory/lexirumah-data#119]
I'm trying to figure out which release to include in CLICS3. v2.2.6 has the CLDF validation issues I pointed out earlier, v2.2.9 apparently has quite some regressions - re-introducing problems with CLDF validation. Any ideas?
Generally, I think it would be good practice only to release versions where the CLDF dataset validates?

**Comment by Anaphory** [comment]
That would be good practice indeed, but I'm not very wise today. In the process of trying to sort out a working Zenodo JSON file, I seem to have messed up some other things. One part of it is me messing with cognate classes, that's also what broke v2.2.9 and what I'm explicitly working on fixing right now.

If the cognate coder was not as slow as it is with our gazillion of languages, I would promise to be done with a version 3.0.0 today and suggest you take that – but that process takes several days now, so I think I will create a 3.0.0 without consistent cognate codes, much to the dismay of my colleagues, and suggest you take that.

(The major version number change comes from us systematically changing the form IDs from numerical to more verbose `language-concept-synonymcount` IDs)

**Comment by Anaphory** [comment]
I got a dataset that I'm reasonably comfortable with, including a current snapshot of the still-running autocoder. If it succeeds the continuous integration tests, I'll create it as v3.0.0 and suggest you use that for CLICS 3.

**Comment by Anaphory** [comment]
The latest commit seems acceptable to me. Please take [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3537977.svg)](https://doi.org/10.5281/zenodo.3537977) for CLICS3, if you don't find any other issues I'm overlooking in there.

**Comment by chrzyki** [comment]
Thanks for sorting that out! Just tested everything and works flawlessly!

**Comment by xrotwang** [comment]
Thanks!

**Comment by xrotwang** [comment]
@Anaphory could you add v3.0.0 to the CLICS community on Zenodo as well?
