### ISSUE TITLE
incorrect Talur form

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#120]
https://lexirumah.model-ling.eu/values/ilwa1238-sun-1 is _leo_ when it should be _lelo_ in all forms.

**Comment by OwenAmarasi** [comment]
Actually, this whole list is a clone of the Aputai list

**Comment by Anaphory** [comment]
What shall we do about this?

(By the way, hi again!)

**Comment by Anaphory** [comment]
Fixed it in here, not yet in the published versions (Zenodo, Web)
