### ISSUE TITLE
Fix Kodi and Lamboya transcription

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#122]
The forms column for Kodi and Lamboya reflects an old (incorrect) analysis of the data and needs to be cleaned up. Mainly the following things:

- [ ] Lamboya geminate consonants (with ː) should be single (but the orthography column should still reflect a double letter -- in the orthography a double C indicates previous short vowel)
- [ ] Kodi has no aspiration
- [ ] Kodi [ɲ] should be ny in the orthography column

I understand this is not something that can be ‘fixed’ right now, but I thought I would leave a note here for when/if LexiRumah gets revived.

**Comment by Anaphory** [comment]
That need of Lamboya sounds complicated. Probably better done by hand than trying to hack together a regex?

The Kodi case is strange indeed. We have

```
kodi1247-bamboo-1,kodi1247,bamboo,ʔoŋgol,ʔoᵑgol,onggol,ʔ o ⁿg o l,,lovestrandballe18
kodi1247-bamboo-2,kodi1247,bamboo,potːʰo,potːʰo,potto,p o tʰː o,,lovestrandballe18
```
and in the source https://catalog.paradisec.org.au/collections/JL4/items/Kodi_WL403all there is indeed no trace of the aspiration. I don't know where they come from, shall I just **remove all of them**?
```
<ANNOTATION>
<REF_ANNOTATION ANNOTATION_ID="a9896" ANNOTATION_REF="a6602">
<ANNOTATION_VALUE>ʔoŋgol</ANNOTATION_VALUE>
</REF_ANNOTATION>
</ANNOTATION>
<ANNOTATION>
<REF_ANNOTATION ANNOTATION_ID="a9897" ANNOTATION_REF="a6603">
<ANNOTATION_VALUE>potːo</ANNOTATION_VALUE>
</REF_ANNOTATION>
</ANNOTATION>
```

The ɲ issue comes from
https://github.com/lessersunda/lexirumah-data/blob/476454a37b42f42ea72c9f40bf7280f6398c56e3/cldf/p/kodi1247#L21
and is thus restricted to geminates:
```
kodi1247-door-1,kodi1247,door,ˈɓiɲːa,ˈɓiɲːa,binnya,ɓ i ɲː a,,lovestrandballe18
kodi1247-dry_in_sun-1,kodi1247,dry_in_sun,pambaˈɣariɲ,paᵐbaˈɣariɲ,pambaghariɲ,p a ⁿb a ɣ a r i ɲ,,lovestrandballe18
```
So, should they all be `ɲɲ` in the orthography?

**Comment by OwenAmarasi** [comment]
-Lamboya: Yes, probably best to do by hand.
-Kodi aspiration: yes, delete all aspiration ʰ from the forms column. The original list was supplied by Joey Lovestrand who mis-heard aspiration. I think he updated his transcription (on my recommendation) in between supplying us with the list and uploading it to PARADISEC. Whether aspiration should be removed from the "given as" column, I don't know.
-Kodi enya: My bad this should read " should not be in the orthography column " I'll update it. Instead, enya should be <ny> in this column

**Comment by Anaphory** [comment]
@OwenAmarasi For Lamboya, I have checked that none of the forms have /VːCː/, so I'm free to replace all the Cː→C.
Do I need to make sure that all the /VCV/ are instead /VːCV/ when there wasn't a double consonant? Then we should do that for the next release.

**Comment by OwenAmarasi** [comment]
Yes, you're free to free to replace all the Cː→C.

I had a quick flick through the Lamboya list, and I don't see any instances of /VCV/ though we should probably double check. 

This issue is closed, does this mean that you have replaced Cː→C in the back-end?

**Comment by Anaphory** [comment]
> I had a quick flick through the Lamboya list, and I don't see 
> any instances of /VCV/ though we should probably double check.

Okay! I'll check.

> This issue is closed, does this mean that you have replaced Cː→C 
> in the back-end?

Indeed. I'm just fixing some discrepancies between the alignments 
that come with the judgements and the forms given in the other 
table, and then I'm going to update the points outside Github, 
namely the website and Zenodo.


-- 
Gereon
