### ISSUE TITLE
Numeralbank

### ISSUE THREAD

**Issue by barlowrussell** [Anaphory/lexirumah-data#126]
Hello, I was wondering whether there would be interest in incorporating the numeral data from LexiRumah into Numeralbank (https://github.com/numeralbank). There seems to be a good amount of material in LexiRumah that isn't yet covered by the datasets already associated with Numeralbank. I think it would be a good synergy to connect the two. Anyway, I'm curious to hear what you think. Of course, I'd be happy to provide any additional information, if desired.

**Comment by Anaphory** [comment]
No objections at all, that's what it's there for!

**Comment by Anaphory** [comment]
Transferred this issue to the lexirumah-data repository. I'll get to it (and in the process also fix the two open transcription issues #122 and #125 because if I make a new release, why not) some time this week.

**Comment by Anaphory** [comment]
@Bibiko The new version with those changes is now also [on Zenodo](https://zenodo.org/record/5951917), just like all the previous versions. (The collective DOI for all versions is [10.5281/zenodo.1164782](https://doi.org/10.5281/zenodo.1164782))

What's still missing is SQLite generation and upload to the web database, but that's not a thing you folks need.

**Comment by Bibiko** [comment]
@Anaphory Perfect - thanks a lot.
