### ISSUE TITLE
add comment column

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexirumah-data#15]
As just discussed, the comment column should be added to the word lists and actually also appear in the whole word list view.

**Comment by LinguList** [comment]
if you use that comment field during edictor sessions, you'll see that the most recent version online allows for specific markup (not elaborate now, but will be expanded). So you make right mouse-click and a pop-up opens where you can even write new lines, and use the asterisk to write `*italic*` or `**bold**` as well as using `|s a m p a|` to convert sampa to segmented IPA and `/s@mpa/` should convert to ipa. Will work on more features (e.g., bibliographical rendering via http://bibliography.lingpy.org, or usernames and time stamps).

**Comment by Anaphory** [comment]
Cool stuff!

**Comment by LinguList** [comment]
if you have wishes/suggestions, feel free to file issues, as I'll try to work on this a bit during the next time. As long as it is only regexes, I can easily incorporate...
