### ISSUE TITLE
Idate is off by one

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexirumah-data#20]
Concepts and translations don't match

Check that hand is colexified with five, not four.

Probably the issue with Mengajar (ca. item 411) again, like with Alorese

**Comment by Anaphory** [comment]
@klamermaf We just checked our original Excel word list for Idate. We took it from the `copy AN languages from Flores` file originally, and it's already wrong in there. By the looks of it only for the last few items including numerals, but we don't know where it starts to be wrong and need you telling us which is the first wrong word in http://www.model-ling.eu/lexirumah/languages/idat1237.

**Comment by klamermaf** [comment]
Hi
I can't look in detail at this during the meeting here, but I attach an excel sheet that has the original field notes in it. It may be that something went wrong when the Idata data from this sheet was punt into the one copy AN languages from Flores. Maybe Jiang can have a look to compare? Thanks a million,
M

________________________________

**Comment by OwenAmarasi** [comment]
In the latest update I slotted all the numerals down by one, so the numerals are now correct. But I have not (yet) checked if this affected all following concepts too.

**Comment by OwenAmarasi** [comment]
This is now fixed. I also fixed a number of other issues with the Idate wordlist.
