### ISSUE TITLE
kəlqŋ

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexirumah-data#22]
“Sky” in datasets/lmhlimk20150524wordlist.tsv is given as `kəlqŋ`. I don't know much about phonology, but I doubt that.

**Comment by hannalotte** [comment]
Yes, this looks odd. I suspect a schwa insted of the 'q'. 

In Pampus' dictionary on Lamaholot Lewolema (located close to Lewoingu), I find kələ̃. 

But this will probably be easy to check by relistening to Marian's recording for Lewoingu.

**Comment by klamermaf** [comment]
I checked, it is kələŋ.

**Comment by wujiang720** [comment]
I fixed this and staged the commit. Also for the issue in Wersing 'where'.
