### ISSUE TITLE
Test version of LexiRumah

### ISSUE THREAD

**Issue by klamermaf** [Anaphory/lexirumah-data#32]
- [x] Komodo: funny orthography for item "a few"
 - [x] Source De Jong 1987 has {} in title
 - [x] Language have two columns named "Sources"; is the second one "Orthography in Source"?
 - [x] Komodo: number code in "cooked corn"
 - [x] So'a: no data at all > is the idea to link to Ngada?
 - [x] Tab Cognatesets: empty
 - [x] Tab Sources: funny entries at the bottom of p. 1 (numbers, codes); there is also an entry called "None"
 - [x] Language has column called Region. Some slots are empty. The region names are not consistent, and thus not useable for sorting. Improve by making more consistent, eg. North Alor Tengah > Alor, North Centre; Alor Northwest > Alor, North West, East Pantar > Pantar, East; Central Pantar > Pantar, Central, etc.

**Comment by Anaphory** [comment]
Thank you!

About half of these I may have been aware of, but it's still very good to have this list of all of them.

 - Forms that have numbers are those where we don't have a form from the source, but a comment which we didn't want to remove. I have not yet found a good way to display something less confusing.

**Comment by Anaphory** [comment]
- [x] Something went fundamentally wrong with So'a. I took it out of the archive of imported languages, so we can remember to re-import it if that is necessary.

**Comment by Anaphory** [comment]
Regions were previously automatically generated from Google Maps from the geocoordinates. Google Maps have changed their policies. I have now switched to GeoNames, which seems to have some issues that need manual fixing (maybe even in their database if possible?) but is mostly all right.

**Comment by Anaphory** [comment]
- [x] So'a has been re-imported. Currently, it still has ɓ and ʋ and ˌ in the orthography column.
