### ISSUE TITLE
Lamaholot-Kalikasa wordlist: long vowels

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexirumah-data#34]
I spotted two more long vowels:

1) paat [paːt] ˞'four'
2) maa [maː] `say; if'

**Comment by OwenAmarasi** [comment]
Done, this should appear in the update (scheduled for Thursday). What about lém for ‘five’?

**Comment by hannalotte** [comment]
Yes, léém should also have a double vowel.
________________________________
Van: Owen Edwards [notifications@github.com]
Verzonden: dinsdag 5 februari 2019 10:38
Aan: lessersunda/lexirumah-data
CC: Fricke, H.L.A.; Author
Onderwerp: Re: [lessersunda/lexirumah-data] Lamaholot-Kalikasa wordlist: long vowels (#34)


Done, this should appear in the update (scheduled for Thursday). What about lém for ‘five’?
