### ISSUE TITLE
glottolog codes for C Lamaholot and E Lamaholot

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexirumah-data#35]
I would suggest to change the glottolog codes for Central Lamaholot varieties and Eastern Lamaholot varieties. There is not much evidence to group them together with Western Lamaholot (lama1277).

Central Lamaholot 
- Lewokukun
- Mingar
- Imulolo
- Lewuka
- Kalikasa
- Painara
- Lerek
- Lewopenutu
- Lewotala

Eastern Lamaholot 
- Lewoeleng
- Lamatuka

Following the current glottolog version (which corresponds to my classification suggestions), the following codes would apply:
Western Lamaholot: lama1293
Central Lamaholot: lama1294
Eastern Lamaholot: lama1297

**Comment by Anaphory** [comment]
Oh, right! I had not realized that the Glottolog version including your classification suggestions has been published by now.

**Comment by Anaphory** [comment]
Most of the Glottocodes (not our language IDs, they are fixed, even though they might look like they have glottocodes in there they are essentially arbitrary) for Lamaholot lects are fixed. I had a question on Painara and Lerek, and it is not inconceivable that I mistyped some code.
