### ISSUE TITLE
Speakers for Klamer 2015b

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#39]
The list f speakers for Klamer, Marian. 2015. Field notes on Lamaholot-Lewoingu displays weirdly in the sources:

Speakers: Bernardus Boli Manu [BBM] and Mariyati Manuk [MM] and Yohanes Ola Manuk [YOM] and bibrec['speaker'].split('&')[-1]

**Comment by Anaphory** [comment]
So far, I have no idea where that comes from.

**Comment by Anaphory** [comment]
I think this issue is just with the web interface, moved it there.
