### ISSUE TITLE
Change lect name Nedebang→Klamu

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/lexirumah-data#40]
cf. https://github.com/lessersunda/lexirumah/issues/25

**Comment by Anaphory** [comment]
This needs pointing out to Harald as well, https://glottolog.org/resource/languoid/id/nede1245 does not list Klamu

**Comment by d97hah** [comment]
Ok I'll change to Klamu

Pada tanggal Sen, 4 Feb 2019 pukul 17.18 Gereon Kaiping <
notifications@github.com> menulis:
