### ISSUE TITLE
Klamer & Fricke, 2013 and 2015

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#44]
The Klamer and Fricke source for Hewa should ideallly be separated into _two_ different sources. I take it that the reference to Hanna's fieldwork refers to the fieldwork she did for her MA? If so then we can take that as the Fricke source. Presumably anything not found in her appendix comes from Marian's fieldwork?

So we can split this into two sources:

Klamer, Marian. (2015) Field notes on Hewa.

and

Fricke, Hanna. (2014) Topics in the grammar of Hewa: A variety of Sika in Eastern Indonesia. Master’s thesis, Leiden University.

A task for someone to do is to check which words in this list don't occur in Hanna's MA thesis. Then (presumably) the residue was collected by Marian. i.e. [pahɑk] ‘slap’ isn't in Hanna's MA, so I presume it came from Marian's fieldwork. (It also records the phonetic detail of the backness of the second [ɑ] which is one characteristic of Marian's fieldnotes.)

**Comment by Anaphory** [comment]
Yes, that sounds like the right approach.
