### ISSUE TITLE
Not yet a lexibank dataset

### ISSUE THREAD

**Issue by xrotwang** [Anaphory/lexirumah-data#58]
Hi @Anaphory, I just accepted lexirumah v2.1.1 within the lexibank community on ZENODO, but upon further inspection, it seems v2.1.1 isn't really a lexibank dataset yet. E.g. it does not define a `lexibank.dataset` entry point, and CLDF validation reports the following warning:
```
$ cldf validate cldf/Wordlist-metadata.json 
WARNING invalid CLDF URI: http://cldf.clld.org/v1.0/terms.rdf#region
```

**Comment by Anaphory** [comment]
Oh, right, I had meant to create that entry point. Can you kick it out of the community again for this release?

**Comment by xrotwang** [comment]
Tried to, but that seems to be impossible :) So we better aim for a quick bug-fix release ...

**Comment by xrotwang** [comment]
Maybe you could merge my PR and re-release as v2.1.2?

**Comment by Anaphory** [comment]
I still don't understand how to properly make a lexibank dataset. I have pushed a changed version of [lexibank.py](https://github.com/lessersunda/lexirumah-data/blob/lexibank/pylexirumah/lexibank.py), trying to use the same metadata file, but I don't see where the actual loading of the data happens and how to influence that, and the metadata is only loaded when running `lexibank ls`, not with `lexibank load lexirumah`, which I find confusing.

**Comment by Anaphory** [comment]
The `cmd_install`, by the way, is taken from one of the existing datasets. I assumed I would see what it does and then fix it, but I cannot see it being called at all.

**Comment by xrotwang** [comment]
Yes, the call chain is a bit implicit. You have to run the `lexibank curate` command, to start a curation REPL. Then you call the dataset specific curation commands in the REPL, e.g. `makecldf lexirumah`. While this may look like overkill, this turned out to be the simplest (?) way of getting
- tab-completion for commands
- tab-completion for datasets
- caching of Glottolog and Concepticon data across calls of curation commands for multiple datasets

**Comment by xrotwang** [comment]
The way you overwrote `metadata` looks ok to me. What exactly is the problem with this? Of course this mechanism will clash with using lexibank for the CLDF creation, because running `makecldf` will first wipe out your `cldf/` directory - so at that point your metadata source would have been deleted.

**Comment by xrotwang** [comment]
`lexibank load` does only access the CLDF dataset. So if you consider the order of workflow steps, it should not be too confusing that `load` doesn't access a dataset's `metadata` attribute. One could argue that `pylexibank` should be two separate tools - one to create lexibank conformant CLDF datasets, and one aggregating these in a sqlite database - but then you could just regard `lexibank curate` and `lexibank load` as these separate tools.

**Comment by Anaphory** [comment]
That's all well, it's just that I wouldn't know where to find the workflow, so I was trying and failing to understand it from looking at the code. Which means that I still don't know what functionality I need to implement and how to test it.

 - `lexibank curate`'s `dbload lexirumah` does something
 - I see it fail if eg. there are duplicate IDs
 - I see it take a long time when I run it with my validated CLDF dataset
 - When it's done, and I run `lexibank db`→`.dump`, there is data in the database, but that data is  a translation of the dataset with its original column names (like `Lect_ID` for the `languageReference), not paying attention to `propertyURL`s and such like. I would have expected an error concerning mismatched table schemata, at least.
 - `Dataset.cmd_install` hasn't been run

**Comment by xrotwang** [comment]
ok, I agree that not paying attention to `propertyUrl` is bad style and lazy. The DB load assumes CLDF which was created using pylexibank - which it should not. I'll file an issue for this on `pylexibank`. For lexirumah, I guess, the main question to answer is whether you want to create the CLDF via pylexibank or not.

**Comment by Anaphory** [comment]
I doubt that I want to create the CLDF via pylexibank. I already have CLDF, with some specific desired properties, so why would I want to convert it? I would much rather have a generic import script that can be pointed to an existing CLDF metadata file, and will either import that as lexibank dataset or complain about the reason why it can't (eg. no conceptlist given, tokenization missing, etc.)

**Comment by xrotwang** [comment]
In the future, [RTFM](https://github.com/lexibank/lexibank#the-lexibank-workflow-and-pylexibank) should do the trick - but we are not there yet :-1:

**Comment by Anaphory** [comment]
Will https://github.com/lexibank/pylexibank/issues/66 also deal with looking at whether a `segments` column exists, in which case it won't need orthography or a tokenization function?

**Comment by xrotwang** [comment]
Hm. The tokenization using an orthography profile happens at CLDF creation. So yes, the DB loading will not need an orthography. But it also won't use one for tokenization if one were provided.

**Comment by Anaphory** [comment]
My dataset contains a CLDF segments column. Is there anything else I might want to pay attention to (at some point, I'd want `pylexibank` to not overwrite the existing dataset, but that's not a main issue right now), or is LexiRumah fine as lexibank dataset for now, and the remainder needs to be fixed in `pylexibank`?

**Comment by xrotwang** [comment]
I'll try to find time to fix pylexibank later today, and then check whether clics works on top of lexirumah. At the moment, this would be my definition of "fine as lexibank dataset" :)

**Comment by xrotwang** [comment]
Ok, https://github.com/lexibank/pylexibank/issues/66 is fixed now. Will check whether this works for lexirumah later today.

**Comment by Anaphory** [comment]
So, is this fine now? May I publish it as v2.1.2?

**Comment by xrotwang** [comment]
Yes, think so. (The many branches are a bit confusing,  but you'll pick the
right one for release, I guess :) )

Gereon Kaiping <notifications@github.com> schrieb am Mo., 25. Feb. 2019,
05:16:

**Comment by chrzyki** [comment]
@Anaphory two minor things for Lexibank compliancy:

- Could you change the ID column in the metadata from INT to STRING? e.g.

```
{
    "datatype": "integer",
    "propertyUrl": "http://cldf.clld.org/v1.0/terms.rdf#id",
    "required": true,
    "name": "ID"
},
```

and everywhere else where this is used as a key.

- There are multiple languages with empty `forms`, could these be added?

Thanks!

**Comment by Anaphory** [comment]
Yes, I'll change the datatype of ID.

As far as empty forms are concerned, those should be cases where the actual form is not attested (either the concept does not exist in the language, eg. SNOW, or we just don't know it because the dictionary does not list it), but we have some metadata about it, mostly comments, which we would want to preserve. What would you suggest doing about that?

**Comment by xrotwang** [comment]
Hm. We do have the assumption that no empty forms appear in lexibank datasets, and the pylexibank machinery for creating the CLDF actually prevents that from happening. So, ideally, I'd say you should add metadata about non-existing forms into a separate table. I think the semantics of "here's the entry for the word that isn't there" are just counter-intuitive and screw up even simple things like summary statistics about a dataset.

**Comment by Anaphory** [comment]
Separate table sounds like an appropriate compromise, I'll see that I get it done soon.

**Comment by Anaphory** [comment]
Fixed, and it will be part of the next release within a few days, as well.
