### ISSUE TITLE
‘Language template´ has a whole lot of gibberish after the name

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#66]
This gibberish to be precise:

b2b083ed6748aa39887049c3722dc63e1a174a77

There is not problem with the functionality, its just weird!

**Comment by Anaphory** [comment]
It might be a reference to a specific Git commit.

**Comment by OwenAmarasi** [comment]
OK, it doesn't need to be fixed. It was just a pain when I downloaded the folder.

**Comment by OwenAmarasi** [comment]
This is only an issue when I download this from the ‘lexirumah data’ branch, no the Lessersunda main page.
