### ISSUE TITLE
R > ʀ

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexirumah-data#7]
As far as I know the 'R' in the proto-languages should be represented by 'ʀ' which is the IPA symbol for an uvular trill. I am noticing this in particular because edictor does not recognize 'R' but it does recognize 'ʀ'.

**Comment by LinguList** [comment]
yes, mostly, only valid IPA is recognized (and it may even at times be not, due to certain things I have not yet spotted, like click sounds, etc.)

**Comment by Anaphory** [comment]
Will do! I wasn't sure that "R" wasn't generic notation for an R-like sound, but I have added a line to replace R→ʀ in my tools now. Because I'm also trying to fix some other issues with my round-trips, it might take yet some more time till it comes round.

**Comment by LinguList** [comment]
BTW: if you encounter things which are clear IPA and are NOT properly displayed (that is: reddish), please file an issue with EDICTOR, so I can adjust them. Ideally, one could customize it, but unless I have support with a programmer in my project, I won't be able to fix the bigger things...

**Comment by Anaphory** [comment]
Will do.

**Comment by hannalotte** [comment]
Great, thanks!

**Comment by hannalotte** [comment]
Two further non-IPA symbols I noticed:

- ε > ɛ (This looks almost the same but apparently, it is a different symbol and the one now used is not IPA)
- Abui uses ä for a certain vowel but I don't know which IPA symbol should be used instead.

**Comment by Anaphory** [comment]
I do have an ε > ɛ fix.

⟨ä⟩ is in principle a valid IPA vowel, it's just /a/ with the centralization modifier diacritic /¨/, but the same thing that normalizes all other problems (also capital ⟨Ɂ⟩ > ⟨ʔ⟩, various encodings of affricates, the ⟨ε⟩ > ⟨ɛ⟩ substitution etc.) does also remove the diacritic, to simplify things.

I'll have a look for why you might not see these cleanups.

**Comment by hannalotte** [comment]
Okay, I see ... so the ä woudl be something to be fixed by edictor? at least in my representation, ä appears in read, thus not recognized as IPA symbol.

**Comment by LinguList** [comment]
The coverage is not full, as I have not all IPA diacritics in there, but this may change sooner than later. ä is usually, however, a wrong annotation, as many linguists use it to denote something like @Anaphory mentioned, or also some sound like æ. Even if it's "valid" IPA, it may still be wrong. The current list is based on the sounds that occur in PBase, a larger database with phoneme inventories by Mielke (2008), and I have manually extended it, but I plan to replace it with a dynamic evaluation in the future.
