### ISSUE TITLE
Double vowels in ‘monosyllables’ for languages of Flores

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#72]
The following languages need this:

- [x] Komodo
- [x] Manggarai
- [x] Rongga
- [x] Ngadha
- [x] Nga'o (Oja)
- [x] Nga'o (Watumite)
- [x] Keo
- [x] Nage
- [x] Palu'e
- [x] Lio

Possibly also Rongga, though I manually doubled these when I was fixing other Rongga things, though I might have missed some.

**Comment by Anaphory** [comment]
For a few of these, the issue is as follows: At some point we decided to reset forms. We should not have done this given that there were long monosyllabics among those forms.

commit 50ef2b637d5ca88b3deabbda922ec8a9789093e5
Author: Gereon Kaiping <g.a.kaiping@hum.leidenuniv.nl>
Date:   Tue Jan 15 17:52:43 2019 +0100

    Reset more forms

**Comment by OwenAmarasi** [comment]
Yes, I remember doing this now

**Comment by OwenAmarasi** [comment]
When you get a chance, send an export of all the (easily findable) monosyllables to me, or put the list here. Another thing to watch out for is monosyllables in compounds; i.e. Ngadha <lo kadzu> = /loː kad͡zu/ so you might also need to do a search before _

**Comment by Anaphory** [comment]
So, all matches of `[,_][^aeiouɛə]*[aeiouɛə]*[^aeiouɛə]*[,_]`? I can do that.

**Comment by OwenAmarasi** [comment]
Yes, I'm pretty sure that's what I'm looking for.

Also, the testing site is super-hepful! I got *way* too distracted
yesterday making minor changes...

All the best,
Owen

**Comment by Anaphory** [comment]
That's a lot, that's 12249 candidate forms.
[monosyllabic.txt](https://github.com/lessersunda/lexirumah-data/files/3076187/monosyllabic.txt)

**Comment by Anaphory** [comment]
Although 5000 of these have two vowels, leaving 7483
[monosyllabic.txt](https://github.com/lessersunda/lexirumah-data/files/3076190/monosyllabic.txt)
