### ISSUE TITLE
hyphens deleted in orthography

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#83]
Hyphens in the  ‘given as’ column get converted to pluses, then deleted in the orthography column. Add orthography rule to fix, I guess. But more broadly, the ‘orthography’ column should just clone the ‘given as’ column. Maybe a copy-paste is the best solution.

**Comment by OwenAmarasi** [comment]
Actually, this issue is broader than just Dhao. It also affects other languages in Timor (i.e. those of Rote, What is the best way to deal with this? We want the hyphens in the ‘given as’ to turn into pluses in the form, then into hyphens for the orthography.

**Comment by OwenAmarasi** [comment]
I've assigned you as it seems likely you know an obvious solution that eludes me. I guess the ‘general’ profile is eating up all the pluses? Right?

**Comment by Anaphory** [comment]
For Dhao, it's Dhao's orthography profile.
https://github.com/lessersunda/lexirumah-data/blob/ae7e8870d78a7951bcb79da94663a13dd4385005/cldf/lects.csv#L87

I thought we did not want to mark morpheme boundaries unless we have reduplictations (which is a separate issue we haven't started dealing with)? For Dhao, it's this line:

https://github.com/lessersunda/lexirumah-data/blob/ae7e8870d78a7951bcb79da94663a13dd4385005/cldf/p/dhao1237#L38

**Comment by OwenAmarasi** [comment]
Some languages (eratically?) use a hyphen for certain compounds in their orthographies. 

Dhao should be fixed -- I just copied the ‘given as’ column (after fixing a few issues) into the ‘orthography’ column.
