### ISSUE TITLE
alignment field in tap-aligned.tsv

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexirumah-data#9]
Some fields that store the alignment seem to have taken the comment field now, instead of the IPA field:

![afbeelding](https://cloud.githubusercontent.com/assets/22792492/26163216/47a89294-3b29-11e7-92a8-036e6c37b2b9.png)

**Comment by Anaphory** [comment]
Oh, no, that is West Pantar messing up things again, not the comments column. I thought I had fixed the `nan` values in alignments.

**Comment by hannalotte** [comment]
Ah, I see ... but it is not only in Western Pantar, I also found cases in other languages.
