### ISSUE TITLE
Initial glottal stops after stress aren't deleted

### ISSUE THREAD

**Issue by OwenAmarasi** [Anaphory/lexirumah-data#93]
Can you give me a list of all languages which have forms in which initial _ˈʔ occurs?

Then I can determine which ones (e.g. those in Timor) need this removed orthographically.

**Comment by Anaphory** [comment]
```
$ grep '[_,]ˈʔ' forms.csv | cut -f 2 -d , | sort -u
adan1251-otvai
alor1247-baran
buna1278-malia
keda1252-leuba
kelo1247-hopte
kema1243
laka1255
lama1277-adona
lama1277-lewoi
mamb1306
sarr1247
soaa1237
teiw1235
tetu1245-suai
tetu1246
tuku1254
```

“Give me all unique entries of the second field (i.e. language ID), comma-separated, of every line in `forms.csv` that contains either `,` or `_` (i.e. word boundary or the beginning of the form) followed by `ˈʔ`.”

**Comment by OwenAmarasi** [comment]
- [x] adan1251-otvai
- [x] alor1247-baran
- [x] buna1278-malia
- [ ] keda1252-leuba
- [x] kelo1247-hopte
- [x] kema1243
- [x] laka1255
- [x] lama1277-adona
- [x] lama1277-lewoi
- [x] mamb1306
- [ ] sarr1247
- [ ] soaa1237
- [ ] teiw1235
- [x] tetu1245-suai
- [x] tetu1246
- [x] tuku1254
