### ISSUE TITLE
Wordlists East Timor Klamer2002?

### ISSUE THREAD

**Issue by hannalotte** [Anaphory/lexirumah-data#96]
Are the Eastern Timor lists from Marian (Idate, Kemak, ...) really from 2002? I thought they were more recent, 2016??

**Comment by OwenAmarasi** [comment]
I believe they are. These are lists that Marian collected for a project which was going to be in East Timor, but then she shifted to Alor-Pantar instead for ¿political? reasons, and the rest is history.
